package ir.smmh.jile.math.geometry;

import ir.smmh.jile.math.numbers.Real;

/**
 * A {@link Metric} is a function that defines a concept of distance between any
 * two members of a set, which are usually called points. A metric satisfies the
 * following properties:
 *
 * <ul>
 * <li>Identity of indiscernibles: {@code d(a, b) = 0} iff {@code a = b}</li>
 * <li>Symmetry: {@code d(a, b) = d(b, a)}</li>
 * <li>Subadditivity, or triangle inequality:
 * {@code d(a, b) <= d(a, m) + d(m, b)}</li>
 * </ul>
 * <p>
 * Given the above three axioms, we can also deduce that all distances are
 * non-negative: {@code d(a, b) >= 0}</li>
 *
 * <p>
 * A {@link Metric} or "distance function" is a function that gives a distance
 * between any given two elements of a set. A set with a metric is called a
 * {@link MetricSpace}. A metric induces a {@link Topology} on a set, but not
 * all topologies can be generated by a metric. A topological space whose
 * topology can be described by a metric is called metrizable.
 * <p>
 * One important source of metrics in differential geometry are metric tensors,
 * bilinear forms that may be defined from the tangent vectors of a
 * differentiable manifold onto a scalar. A metric tensor allows distances along
 * curves to be determined through integration, and thus determines a metric.
 *
 * @see https://en.wikipedia.org/wiki/Metric_(mathematics)
 */
public interface Metric<M> {
    Real distance(M a, M b);
}
